### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by MarauderXtreme** [JustusAdam/justusadam.github.io#5]
I've not found a "Datenschutzerklärung" needed at least in Germany for Websites. I think you just forgot to migrate it from your old site. You know where to find the generator. ^^

**Comment by JustusAdam** [comment]
Only if your site has users that may enter data.

**Comment by MarauderXtreme** [comment]
On my site I have two paragraphs like this:

> Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.
> 
> Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.

Source: [eRecht24](http://www.e-recht24.de/muster-datenschutzerklaerung.html)

I think should be on your site even when you users don't enter data to it. At least link Githubs won [Privacy Policy](https://help.github.com/articles/github-privacy-policy/)

**Comment by JustusAdam** [comment]
There is absolutely no reason. I do not save private user data of any form, so there's no reason for me to tell them that I will protect that. Furthermore I do not use any trackers, which could potentially collect usage data.

**Comment by MarauderXtreme** [comment]
Well okay. So you want that your Imprint data is used for sending you advertisement or other things not related to the concerns of an imprint.

**Comment by JustusAdam** [comment]
That's not what a "Datenschutzerklärung" is for. It does not protect me, it is a disclaimer how _I_ (don't) protect the users data. 

A "Datenschutzerklärung" has nothing to do with publicly available data. 

What you're perhaps thinking of is a license.

**Comment by MarauderXtreme** [comment]
Since this is a widely used example I think this is the appropriate position to put this. A license just protects your self created work. Your adress is not really your self created work.  
If you do not want in no case this on your website it is okay. It's up to you. I just have seen it and wanted to provide my thoughts about it.
